app:
  candidate:
    name: "Devanjan Chatterjee"
    regNo: "22BCE7949"
    email: "devanjan.22bce7949@vitapstudent.ac.in"
  # If the submission API expects "Bearer <token>", set this to true.
  # The challenge statement shows just the raw token, so default is false.
  submission:
    useBearerPrefix: false

endpoints:
  generate: "https://bfhldevapigw.healthrx.co.in/hiring/generateWebhook/JAVA"

# timeouts (optional)
spring:
  main:
    web-application-type: none

